# -*- coding: utf-8 -*-
"""score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vZn9OGsZFsLDFMwW5Yc88M64I7S8CnI1
"""

score=input().spliut()
min=0
max=0

for s in score:
  if int(s)<60:
    countF += 1
    if s>max:
      max=s
    if s<min:
      min=s
print(countF)
print(min,max)