# -*- coding: utf-8 -*-
"""score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vZn9OGsZFsLDFMwW5Yc88M64I7S8CnI1
"""

score=input().spliut()

countF=0
for s in score:
  if int(s)<60:
    countF += 1
print(countF)